version: '3'

services:
  planner:
    image: gotex
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - YEAR=     #Generates for next year unless alternate year set
      - PREVIEW=0  #Generate a preview of the planner 
    volumes:
      - .:/go/src/app:rw
